![](https://peakpowersavers.com/img/program-details/time-of-use-program-chart.jpg)

In [51]:
meter_reads="""Jan 25, 2018 	55052 	Actual
Dec 21, 2017 	53519 	Actual
Nov 21, 2017 	52181 	Actual
Oct 23, 2017 	51139 	Actual
Sep 24, 2017 	50078 	Actual
Aug 23, 2017 	48966 	Actual
Jul 25, 2017 	47815 	Actual
Jun 25, 2017 	46498 	Actual
May 24, 2017 	45346 	Actual
Apr 25, 2017 	44518 	Actual
Mar 26, 2017 	43739 	Actual
Feb 23, 2017 	42900 	Actual
Jan 26, 2017 	41956 	Actual
Dec 26, 2016 	40928 	Actual
Nov 27, 2016 	39771 	Actual
Oct 23, 2016 	38383 	Actual
Sep 22, 2016 	37096 	Actual
Aug 23, 2016 	35724 	Actual
Jul 25, 2016 	34188 	Actual
Jun 22, 2016 	32371 	Actual
May 24, 2016 	31329 	Actual
Apr 24, 2016 	30281 	Actual
Mar 26, 2016 	29212 	Actual
Feb 24, 2016 	28154 	Actual"""

In [72]:
reads = list()
dates = list()
for line in meter_reads.splitlines():
    date_, read_, _ =line.split("\t")
    
    date = datetime.datetime.strptime(date_, "%b %d, %Y ")
    read = int(read_)
    reads.append(read)
    
    dates.append(date)

In [53]:
import numpy as np

In [54]:
reads_np = np.array(reads[:-1:])

In [55]:
np.diff(reads_np)

array([-1533, -1338, -1042, -1061, -1112, -1151, -1317, -1152,  -828,
        -779,  -839,  -944, -1028, -1157, -1388, -1287, -1372, -1536,
       -1817, -1042, -1048, -1069])

In [56]:
np.abs(np.diff(reads_np))

array([1533, 1338, 1042, 1061, 1112, 1151, 1317, 1152,  828,  779,  839,
        944, 1028, 1157, 1388, 1287, 1372, 1536, 1817, 1042, 1048, 1069])

In [59]:
usages = np.abs(np.diff(reads_np))

usages

array([1533, 1338, 1042, 1061, 1112, 1151, 1317, 1152,  828,  779,  839,
        944, 1028, 1157, 1388, 1287, 1372, 1536, 1817, 1042, 1048, 1069])

In [60]:
for usage in usages:
    break

In [61]:
usage

1533

In [62]:
usage-600

933

In [63]:
9.39*600

5634.0

In [64]:
12.68*933

11830.44

In [66]:
(9.39*600+12.68*(usage-600))/100

174.64440000000002

In [67]:
8.28*(usage)/100

126.9324

In [68]:
max(usages)/30

60.56666666666667

In [73]:
for idx, usage in enumerate(usages):
    break

In [74]:
dates[idx]

datetime.datetime(2018, 1, 25, 0, 0)